### ISSUE TITLE
友言评论无法使用

### ISSUE THREAD

**Issue by Dr-Harris** [WongMinHo/hexo-theme-miho#19]
我已经注册获取到了友言id并且配置好了，但是页面没有效果，并且浏览器会输出警告
`
A parser-blocking, cross site (i.e. different eTLD+1) script, http://v3.jiathis.com/code/plugin.client.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
`

**Comment by WongMinHo** [comment]
谢谢提醒，接下来会解决这个问题~

**Comment by WongMinHo** [comment]
@Dr-Harris 你的网站是https吗？我看了一下友言好像不支持https

**Comment by Dr-Harris** [comment]
是的，是挂在github上的

**Comment by WongMinHo** [comment]
那应该就是因为这个原因加载不了了，你可以改用畅言
