### ISSUE TITLE
全文检索

### ISSUE THREAD

**Issue by daomengkiller** [WongMinHo/hexo-theme-miho#23]
现在的目前搜索功能太弱了，能否有全文检索功能，即文中的词语都能检索，不只是标题

**Comment by WongMinHo** [comment]
这个功能暂时没有，后续考虑~

**Comment by WongMinHo** [comment]
@daomengkiller 已经支持全文搜索了，你拉取下最新代码~

**Comment by daomengkiller** [comment]
先谢谢，但是还有几个问题
1.全文搜索不是很好用，能否提示，搜索结果提示在哪篇文章具体那一段，缩略显示
2.公式在电脑上的浏览没显示，手机正常
3.主页的每篇文章cover图片，能否路径能否使用文章的图片路径，因为想每篇文章cover图片不一样，但是图片一多，管理不方便。
