### ISSUE TITLE
畅言评论问题

### ISSUE THREAD

**Issue by williamHappy** [WongMinHo/hexo-theme-miho#27]
请问一下 ，我的畅言评论功能，为什么评论了 ，一刷新页面就没有了，在畅言后台，也接收不到评论的小时，你这个评论系统是怎么配置的，只在_config.yml中配置畅言的appid和appkey就行了吗，还是还需要配置别的东西？
![image](https://user-images.githubusercontent.com/19304825/39304132-3f2e0786-498b-11e8-99dc-02f590667ffc.png)

**Comment by WongMinHo** [comment]
你在畅言后台看下评论是不是未审核或者已删除。
