### ISSUE TITLE
侧边图标无法显示

### ISSUE THREAD

**Issue by LiZeC123** [WongMinHo/hexo-theme-miho#28]
作者你好, 最近更新了博客, 发现侧边栏的图标无法显示了, 这导致了搜索, 标签等界面无法使用, 如下图所示:
![default](https://user-images.githubusercontent.com/11004853/40277396-13d05890-5c51-11e8-9600-0efa0b1fe929.JPG)

我看了一下html代码, 发现 `//cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css`  这个css文件无法访问, 然后发现作者你的博客网站这个css文件是可以访问的(在浏览器查看源代码页面上点击链接)
 
经过调试发现, 如果之前可以成功加载`font-awesome.min.css` , 之后就可以正常显示图标, 因此基本可以认定是这个文件的问题.

由于我没学过前端技术,所以我也不知道这个问题应该如何解决, 希望能和您探讨探讨.

另外,我的博客地址是 http://lizec.top/

**Comment by WongMinHo** [comment]
你好，我打开你的博客显示正常

**Comment by LiZeC123** [comment]
我大概测试了一下, 如果可以成功加载一次, 那么就可以显示图片. 所以你可以在我的页面上强制刷新一下,这样应该就不能显示了.

另外我刚刚搜索到了这个帖子 https://www.v2ex.com/t/455850
看这讨论, 很有可能是CDN的配置出现问题了,所以不能访问.  按照其中的讨论,换了 `font-awesome.min.css` 的CDN以后, 现在可以显示图片了, 但是按钮还是不能点, 不知道按钮是依赖哪一个js文件, 如果可以的话,我想先换一个试试.

**Comment by LiZeC123** [comment]
>您好： 
>
> 非常感谢您对 BootCDN 的支持！也非常抱歉给您带来的麻烦！ 
> 
> BootCDN 自上线提供服务以来，我们一直在针对违法网站（色情、盗版、赌博、垃圾广告）进行清理，所以我们的黑名单非常庞大， 
> 而近期由于域名商低价促销 cc、top 等非常规域名，导致大量违法网站制作者采用了大量 cc、top 类域> 名，导致我们的黑名单已经到达了极限， 
> 不得已，我们只能对这类域名全部屏蔽。如果方便的话，建议您更换成常见的 com、net、cn、org 类 域名或者请更换 cdn。 
> 
> 如果您是商业应用，建议购买商业 cdn 产品。 
> 
> 给您造成的麻烦再次深表歉意！

所以最终的结果就是CDN被屏蔽了, 所以我之后找一找其他的CDN吧
