### ISSUE TITLE
文章后面的评论怎么开启？

### ISSUE THREAD

**Issue by oierlin** [WongMinHo/hexo-theme-miho#34]
文章后面的评论怎么开启？

**Comment by WongMinHo** [comment]
在_config.yml文件的# Comments | 评论下面配置

**Comment by oierlin** [comment]
> 在_config.yml文件的＃Comments | 评论下面配置

在畅言的网站上注册需要ICP备案号，这个怎么弄？

**Comment by WongMinHo** [comment]
畅言是需要ICP备案才能用的。
