### ISSUE TITLE
百度统计请求报错

### ISSUE THREAD

**Issue by amosyo1994** [WongMinHo/hexo-theme-miho#38]
> 很感谢作者开发了这款主题，感谢！

### 问题

在使用主题过程中，我发现百度统计的请求报错，不知道是否是我配置问题（对比百度统计官网无错误）。

烦请作者有空帮忙排查下，谢谢。

### 博客地址

```
https://blogs.amosyo.com/
```

### 错误

![image](https://user-images.githubusercontent.com/44084229/49431256-07322400-f7e8-11e8-9d75-5770047ce037.png)
![image](https://user-images.githubusercontent.com/44084229/49431262-0dc09b80-f7e8-11e8-82f3-26251032e36f.png)

**Comment by WongMinHo** [comment]
你好，我看了你博客，没发现百度统计报错的问题

**Comment by amosyo1994** [comment]
@WongMinHo 好的  打扰你了 可能是广告拦截插件的问题   我关掉issue
