### ISSUE TITLE
Article configuration example 內的 cover_picture 問題

### ISSUE THREAD

**Issue by 5SMNOONMS5** [WongMinHo/hexo-theme-miho#8]
Article configuration example
```
---
title: Hello World
date: 2017-06-18
categories: First
tags:
    - First
    - Second
cover_picture: /images/banner.jpg
---
```
請問 cover_picture 是改變當前文章的 banner 圖片嗎?
因為我想要不同文章有不同的 banner

**Comment by 5SMNOONMS5** [comment]
我找到問題了，是 URL Address 有錯
![s__20897796](https://user-images.githubusercontent.com/8379901/33523082-cefb8b78-d838-11e7-94f1-1e80bb70770a.jpg)
我目前改成 
![screen shot 2017-12-03 at 2 47 16 pm](https://user-images.githubusercontent.com/8379901/33523087-e5009616-d838-11e7-81f7-4ba7a72f93f1.png)
這樣寫法沒問題

**Comment by WongMinHo** [comment]
是的，每篇文章都可以配置各自cover_picture封面图

**Comment by 5SMNOONMS5** [comment]
恩  建議版主大大 在 Readme 那邊把 example 從 
`cover_picture: /images/banner.jpg `
替換成 
`cover_picture: http://your/img/url/address `
這樣之後的使用者就可以直接複製使用了

**Comment by WongMinHo** [comment]
恩恩，但是我的博客图片做了防盗链配置，所以其他人用不了~

**Comment by 5SMNOONMS5** [comment]
恩恩 ok
